/*
    Migration 011: Tenant Onboarding

    Adds the single stored procedure that performs the entire "register a new
    organization" transaction: Organization, main Branch, OrganizationSettings,
    owner Person, owner User, tenant-local Roles cloned from the global system
    templates, cloned RolePermissions, the Owner role assignment, an email
    confirmation token, and audit log rows — atomically, or none of it.

    No new tables, columns, or destructive changes. The finalized schema
    (migrations 001-010) already supports the full workflow; every table this
    procedure writes to, and every index it reads from (UX_Organizations_Slug,
    IX_Roles_OrganizationId, UX_Roles_Name_System), already exists.

    NOTE: this is migration 011, not "010" as a generic example might suggest —
    010 was already used by 010_Bilingual_Name_Fields.sql.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

CREATE OR ALTER PROCEDURE tenant.usp_Organization_Register
(
    -- Organization (Id is generated by the caller — Guid.CreateVersion7() —
    -- not by NEWSEQUENTIALID(), matching the rest of the codebase's ID strategy;
    -- see docs/DOMAIN_MODEL.md "Dapper construction strategy").
    @OrganizationId              UNIQUEIDENTIFIER,
    @OrganizationName            NVARCHAR(200),
    @OrganizationArabicName      NVARCHAR(200)  = NULL,
    @OrganizationLegalName       NVARCHAR(200)  = NULL,
    @OrganizationArabicLegalName NVARCHAR(200)  = NULL,
    @Slug                        NVARCHAR(100),
    @LogoUrl                     NVARCHAR(500)  = NULL,
    @OrganizationEmail           NVARCHAR(256)  = NULL,
    @OrganizationPhone           NVARCHAR(30)   = NULL,
    @OrganizationAddress         NVARCHAR(500)  = NULL,

    -- Organization settings
    @TimeZoneId                  NVARCHAR(100),
    @DefaultLanguageCode         NVARCHAR(10),
    @CurrencyCode                CHAR(3),

    -- Main branch
    @BranchId                    UNIQUEIDENTIFIER,
    @BranchName                  NVARCHAR(200),
    @BranchArabicName            NVARCHAR(200)  = NULL,
    @BranchPhone                 NVARCHAR(30)   = NULL,
    @BranchEmail                 NVARCHAR(256)  = NULL,
    @BranchAddress               NVARCHAR(500)  = NULL,

    -- Owner person
    @PersonId                    UNIQUEIDENTIFIER,
    @FirstName                   NVARCHAR(100),
    @LastName                    NVARCHAR(100),
    @ArabicFirstName             NVARCHAR(100)  = NULL,
    @ArabicLastName              NVARCHAR(100)  = NULL,
    @OwnerPhone                  NVARCHAR(30)   = NULL,

    -- Owner user (PasswordHash is already hashed by Infrastructure — see
    -- docs/SECURITY_BASELINE.md; this procedure never sees a raw password)
    @UserId                      UNIQUEIDENTIFIER,
    @Username                    NVARCHAR(100),
    @Email                       NVARCHAR(256),
    @PasswordHash                NVARCHAR(500),

    -- Email confirmation (only the hash is ever passed in — see
    -- docs/SECURITY_BASELINE.md "Token hashing")
    @EmailConfirmationTokenHash    CHAR(64),
    @EmailConfirmationExpiresAtUtc DATETIME2(3),

    -- Request metadata for audit rows
    @CreatedByIp                 NVARCHAR(45)   = NULL,
    @CorrelationId                UNIQUEIDENTIFIER = NULL
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @Now DATETIME2(3) = SYSUTCDATETIME();

    -- ── Pre-checks (cheap reads, before opening a transaction) ──────────────
    IF EXISTS (SELECT 1 FROM tenant.Organizations WHERE Slug = @Slug AND IsDeleted = 0)
    BEGIN
        SELECT
            1                                AS ResultCode,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS OrganizationId,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS BranchId,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS OwnerPersonId,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS OwnerUserId,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS OwnerRoleId,
            CAST(NULL AS BIGINT)             AS EmailConfirmationTokenId,
            CAST(NULL AS DATETIME2(3))       AS CreatedAt;
        RETURN;
    END;

    IF (SELECT COUNT(DISTINCT Name)
        FROM [identity].Roles
        WHERE OrganizationId IS NULL AND IsSystemRole = 1 AND IsDeleted = 0
          AND Name IN (N'Owner', N'Admin', N'Accountant', N'Teacher')) < 4
    BEGIN
        SELECT
            2                                AS ResultCode,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS OrganizationId,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS BranchId,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS OwnerPersonId,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS OwnerUserId,
            CAST(NULL AS UNIQUEIDENTIFIER)   AS OwnerRoleId,
            CAST(NULL AS BIGINT)             AS EmailConfirmationTokenId,
            CAST(NULL AS DATETIME2(3))       AS CreatedAt;
        RETURN;
    END;

    DECLARE @OwnerRoleId UNIQUEIDENTIFIER;
    DECLARE @TokenId BIGINT;

    BEGIN TRY
        BEGIN TRANSACTION;

        INSERT INTO tenant.Organizations
            (Id, Name, ArabicName, LegalName, ArabicLegalName, Slug, LogoUrl, Email, Phone, Address, Status, CreatedAt)
        VALUES
            (@OrganizationId, @OrganizationName, @OrganizationArabicName, @OrganizationLegalName,
             @OrganizationArabicLegalName, @Slug, @LogoUrl, @OrganizationEmail, @OrganizationPhone,
             @OrganizationAddress, 0, @Now);

        INSERT INTO tenant.Branches
            (Id, OrganizationId, Name, ArabicName, Phone, Email, Address, IsMainBranch, Status, CreatedAt)
        VALUES
            (@BranchId, @OrganizationId, @BranchName, @BranchArabicName, @BranchPhone, @BranchEmail,
             @BranchAddress, 1, 1, @Now);

        INSERT INTO tenant.OrganizationSettings
            (OrganizationId, TimeZoneId, DefaultLanguageCode, CurrencyCode, CreatedAt)
        VALUES
            (@OrganizationId, @TimeZoneId, @DefaultLanguageCode, @CurrencyCode, @Now);

        INSERT INTO [identity].Persons
            (Id, OrganizationId, FirstName, LastName, ArabicFirstName, ArabicLastName, Phone, CreatedAt)
        VALUES
            (@PersonId, @OrganizationId, @FirstName, @LastName, @ArabicFirstName, @ArabicLastName, @OwnerPhone, @Now);

        INSERT INTO [identity].Users
            (Id, OrganizationId, PersonId, Username, Email, PasswordHash, IsEmailConfirmed, IsActive,
             FailedLoginAttempts, CreatedAt)
        VALUES
            (@UserId, @OrganizationId, @PersonId, @Username, @Email, @PasswordHash, 0, 1, 0, @Now);

        -- Clone tenant-local roles from the global system templates (set-based —
        -- no C# loop over roles/permissions, per docs/TENANT_ONBOARDING.md
        -- "Performance Requirements").
        DECLARE @NewRoles TABLE
        (
            Id             UNIQUEIDENTIFIER NOT NULL,
            TemplateRoleId UNIQUEIDENTIFIER NOT NULL,
            Name           NVARCHAR(100)    NOT NULL
        );

        INSERT INTO [identity].Roles
            (Id, OrganizationId, TemplateRoleId, Name, ArabicName, Description, IsSystemRole, CreatedAt, IsDeleted)
        OUTPUT inserted.Id, inserted.TemplateRoleId, inserted.Name INTO @NewRoles (Id, TemplateRoleId, Name)
        SELECT
            NEWID(), @OrganizationId, t.Id, t.Name, t.ArabicName, t.Description, 1, @Now, 0
        FROM [identity].Roles t
        WHERE t.OrganizationId IS NULL AND t.IsSystemRole = 1 AND t.IsDeleted = 0;

        -- Clone each cloned role's permissions from its template (set-based).
        INSERT INTO [identity].RolePermissions (RoleId, PermissionId, CreatedAt)
        SELECT nr.Id, rp.PermissionId, @Now
        FROM @NewRoles nr
        INNER JOIN [identity].RolePermissions rp ON rp.RoleId = nr.TemplateRoleId;

        SELECT @OwnerRoleId = Id FROM @NewRoles WHERE Name = N'Owner';

        IF @OwnerRoleId IS NULL
            THROW 51101, 'Tenant onboarding failed: Owner role was not cloned for the new organization.', 1;

        INSERT INTO [identity].UserRoles (UserId, RoleId, OrganizationId, AssignedAt)
        VALUES (@UserId, @OwnerRoleId, @OrganizationId, @Now);

        INSERT INTO [identity].EmailConfirmationTokens
            (UserId, OrganizationId, TokenHash, ExpiresAt, CreatedByIp, CreatedAt)
        VALUES
            (@UserId, @OrganizationId, @EmailConfirmationTokenHash, @EmailConfirmationExpiresAtUtc, @CreatedByIp, @Now);

        SET @TokenId = SCOPE_IDENTITY();

        -- Audit trail — no secrets (no password hash, no token hash/raw value) ever
        -- goes into an audit row; see docs/ARCHITECTURE_RULES.md.
        INSERT INTO audit.AuditLogs
            (OrganizationId, UserId, Action, EntityName, EntityId, IpAddress, CorrelationId, [Source], Succeeded, CreatedAt)
        VALUES
            (@OrganizationId, @UserId, N'Created',     N'tenant.Organizations',              CONVERT(NVARCHAR(100), @OrganizationId), @CreatedByIp, @CorrelationId, N'TenantOnboarding', 1, @Now),
            (@OrganizationId, @UserId, N'Created',     N'tenant.Branches',                   CONVERT(NVARCHAR(100), @BranchId),       @CreatedByIp, @CorrelationId, N'TenantOnboarding', 1, @Now),
            (@OrganizationId, @UserId, N'Created',     N'identity.Users',                    CONVERT(NVARCHAR(100), @UserId),         @CreatedByIp, @CorrelationId, N'TenantOnboarding', 1, @Now),
            (@OrganizationId, @UserId, N'Initialized', N'identity.Roles',                    CONVERT(NVARCHAR(100), @OrganizationId), @CreatedByIp, @CorrelationId, N'TenantOnboarding', 1, @Now),
            (@OrganizationId, @UserId, N'Assigned',    N'identity.UserRoles',                CONVERT(NVARCHAR(100), @OwnerRoleId),    @CreatedByIp, @CorrelationId, N'TenantOnboarding', 1, @Now),
            (@OrganizationId, @UserId, N'Created',     N'identity.EmailConfirmationTokens',  CONVERT(NVARCHAR(100), @TokenId),        @CreatedByIp, @CorrelationId, N'TenantOnboarding', 1, @Now);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        THROW;
    END CATCH;

    SELECT
        0                AS ResultCode,
        @OrganizationId  AS OrganizationId,
        @BranchId        AS BranchId,
        @PersonId        AS OwnerPersonId,
        @UserId          AS OwnerUserId,
        @OwnerRoleId     AS OwnerRoleId,
        @TokenId         AS EmailConfirmationTokenId,
        @Now             AS CreatedAt;
END;
GO

IF OBJECT_ID(N'dbo.SchemaVersions', N'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE MigrationId = N'011')
BEGIN
    INSERT INTO dbo.SchemaVersions (MigrationId, [Name], [Checksum])
    VALUES (N'011', N'Tenant Onboarding', NULL);
END;
GO
